apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-api
  labels:
    app: task-management-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-management-api
  template:
    metadata:
      labels:
        app: task-management-api
    spec:
      containers:
      - name: task-management-api
        image: task-management-api:v1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"